<html>
<head>
</head>
<%@ page import="DBUtilities.GCBChargeBANBean,JavaUtil.*,java.util.Enumeration"%>
<jsp:useBean id="chBAN" class="DBUtilities.GCBChargeBANBean" scope="session"/>
    <%!
        String ButtonPressed,Action;
	Enumeration FormFields;
	String FormField;
	boolean Errors,Success;
        JavaUtil.StringUtil SU = new JavaUtil.StringUtil();
    %>
    <%
      ButtonPressed=(String)request.getParameter("ButtonPressed");
      session.setAttribute("Button",ButtonPressed);
      Action=chBAN.getAction();
      FormFields=request.getParameterNames();

      //Deal with non submit actions first
      //Note that some actions are handled by the javascript generated by HTMLUtil

      if (ButtonPressed.startsWith("Clear"))
      {
	while (FormFields.hasMoreElements())
	{
	  FormField=(String)FormFields.nextElement();
	  chBAN.setParameter(FormField,"");
	}
	chBAN.clearSplitsTable();
        %>
        <jsp:forward page="ChargeBAN.jsp"/>
        <%
      }
      else if (ButtonPressed.startsWith("Re-Use"))
      {
        chBAN.getChargeBan();
        %>
          <jsp:forward page="ChargeBAN.jsp"/>
        <%
      }
      else if (ButtonPressed.startsWith("Create BAN Menu"))
      {
        %>
          <jsp:forward page="CustomerBANMenu.jsp"/>
        <%
      }
      else if (ButtonPressed.startsWith("Back To"))
      {
        %>
          <jsp:forward page="ListBans.jsp"/>
        <%
      }
      else if (ButtonPressed.startsWith("Authorise"))
      {
	chBAN.setUserId((String)session.getAttribute("User_Id"));
        if(chBAN.AuthoriseChargeBAN())
	{

	  session.setAttribute("Message","You have successfully implemented BAN Id :-"+chBAN.getBanIdentifier());
	  %>
	     <jsp:forward page="ListBans.jsp"/>
	  <%
	}
	else
	{
          %>
	    <jsp:forward page="ChargeBAN.jsp"/>
          <%
	}
      }
      else if ((ButtonPressed.startsWith("Return")) || (ButtonPressed.startsWith("Reject")))
      {
	chBAN.setBanStatus(ButtonPressed+"ed");
	chBAN.setAction(ButtonPressed);
	chBAN.setRejectReason((String)request.getParameter("RejectReason"));
	chBAN.setUserId((String)session.getAttribute("User_Id"));
        if(chBAN.updateChargeBan())
	{
	  session.setAttribute("Message",chBAN.getMessage());
	  %>
	     <jsp:forward page="Welcome.jsp"/>
	  <%
	}
	else
	{
	  session.setAttribute("Message",chBAN.getMessage());
	  %>
	     <jsp:forward page="ChargeBAN.jsp"/>
	  <%
	}
      }
      else if (ButtonPressed.startsWith("Cancel"))
      {
	chBAN.setBanStatus("Canceled");
	chBAN.setUserId((String)session.getAttribute("User_Id"));
        if(chBAN.updateChargeBan())
	{
	  session.setAttribute("Message",chBAN.getMessage());
	  %>
	     <jsp:forward page="Welcome.jsp"/>
	  <%
	}
	else
	{
	  session.setAttribute("Message",chBAN.getMessage());
	  %>
	     <jsp:forward page="ChargeBAN.jsp"/>
	  <%
	}
      }
      else if ((ButtonPressed.startsWith("Save Draft")) ||
	      (ButtonPressed.startsWith("Submit")))
      {
	//store form values in Bean
	//FormFields=request.getParameterNames();
	chBAN.clearSplitsTable();

	while (FormFields.hasMoreElements())
	{
	  FormField=(String)FormFields.nextElement();
	  chBAN.setParameter(FormField,request.getParameter(FormField));
	}
	//Validation
	if (!chBAN.isValid(ButtonPressed))
	{
	  %>
	  <jsp:forward page="ChargeBAN.jsp"/>
	  <%
	}
	else
	{
	  if (ButtonPressed.startsWith("Save Draft"))
	  {
	    chBAN.setBanStatus("Draft");
	  }
	  else
	  {
	    chBAN.setBanStatus("Proposed");
	  }
	  //set non form values
	  chBAN.setBanCreatedBy((String)session.getAttribute("User_Name"));
	  chBAN.setUserId((String)session.getAttribute("User_Id"));

	  //Create or amend a BAN

	  if (chBAN.getAction().startsWith("Amend"))
	  {
	    Success=chBAN.updateChargeBan();
	  }
	  else
	  {
	    Success=chBAN.createChargeBAN();
	  }
	  if (Success)
	  {
	    session.setAttribute("Message",chBAN.getMessage());
	      %>
	      <jsp:forward page="Welcome.jsp"/>
	      <%
	    //}
	  }
	  else
	  {//Failed
	    %>
	    <jsp:forward page="ChargeBAN.jsp"/>
	    <%
	  }//end of create
	}//end of if valid
      }
      else
      { //no button pressed, so must have been an autorefresh from a dropdown
	//..still need to store ban values
	  chBAN.clearSplitsTable();
	  chBAN.setErrored("clear");

    	  while (FormFields.hasMoreElements())
    	  {
	    FormField=(String)FormFields.nextElement();
	    chBAN.setParameter(FormField,request.getParameter(FormField));
	  }
        %>
          <jsp:forward page="ChargeBAN.jsp"/>
        <%
      }
    %>
</body>
</html>
